# Generated by Django 5.1.7 on 2025-03-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
