# Generated by Django 5.1.7 on 2025-03-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_image_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='telegram_nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
